Project ERP {
    database_type: 'MySql'
}

Enum "employees_religion_enum" {
  "katholik"
  "islam"
  "kristen"
  "budha"
  "hindu"
  "khonghucu"
}

Enum "employees_martial_status_enum" {
  "married"
  "single"
}

Enum "employees_gender_enum" {
  "female"
  "male"
}

Enum "employee_points_task_type" {
  "production"
  "entertainment"
}

Enum "salaray_type_enum" {
  "month"
  "daily"
}

Enum "employees_education_enum" {
  "smp"
  "sma"
  "smk"
  "diploma"
  "s1"
  "s2"
  "s3"
}

Enum "employees_level_staff_enum" {
  "manager"
  "staff"
  "lead"
  "junior_staff"
}

Enum "relationship_enum" {
  "father"
  "mother"
  "sibling"
  "spouse"
  "child"
  "cousin"
  "nibling"
  "parent_in_law"
  "brother_in_law"
  "sister_in_law"
  "uncle"
  "aunt"
  "grandfather"
  "grandmother"
  "friend"
  "coworker"
  "others"
}

Enum "project_task_worktimes_work_type_enum" {
  "on_progress"
  "review_by_pm"
  "review_by_client"
}

Enum "project_tasks_task_type_enum" {
  "asset3d"
  "compositing"
  "animating"
  "finalize"
}

Enum "projects_event_type_enum" {
  "wedding"
  "engagement"
  "event"
  "birthday"
  "concert"
  "corporate"
  "exhibition"
}

Table "addon_update_histories" {
  "id" bigint [pk, not null, increment]
  "addon_id" int [not null]
  "improvements" longtext [not null]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "addons" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "description" text
  "preview_img" varchar(255) [not null]
  "tutorial_video" varchar(255) [default: NULL]
  "main_file" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "brands" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
}

Table "cache" {
  "key" varchar(255) [pk, not null]
  "value" mediumtext [not null]
  "expiration" int [not null]
}

Table "cache_locks" {
  "key" varchar(255) [pk, not null]
  "owner" varchar(255) [not null]
  "expiration" int [not null]
}

Table "cities" {
  "id" bigint [pk, not null, increment]
  "country_id" bigint [not null]
  "state_id" bigint [not null]
  "name" varchar(255) [not null]
  "country_code" varchar(3) [not null]
}

Table "countries" {
  "id" bigint [pk, not null, increment]
  "iso2" varchar(2) [not null]
  "name" varchar(255) [not null]
  "status" tinyint [not null, default: '1']
  "phone_code" varchar(5) [not null]
  "iso3" varchar(3) [not null]
  "region" varchar(255) [not null]
  "subregion" varchar(255) [not null]
}

Table "custom_inventories" {
  "id" bigint [pk, not null, increment]
  "barcode" varchar(255) [default: NULL]
  "uid" char(36) [not null]
  "build_series" varchar(255) [not null]
  "name" varchar(255) [not null]
  "type" varchar(255) [not null]
  "location" tinyint [not null]
  "default_request_item" tinyint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "custom_inventory_details" {
  "id" bigint [pk, not null, increment]
  "custom_inventory_id" bigint [not null]
  "qty" int [not null]
  "price" double [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "inventory_id" bigint [not null]

  Indexes {
    custom_inventory_id [name: "custom_inventory_details_custom_inventory_id_foreign"]
    inventory_id [name: "inventory_id"]
  }
}

Table "divisions" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "parent_id" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "uid" char(36) [default: NULL]
}

Table "document_templates" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "employee_emergency_contacts" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "phone" varchar(255) [not null]
  "relation" varchar(255) [not null]
  "uid" char(36) [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_id [name: "employee_emergency_contacts_employee_id_foreign"]
  }
}

Table "employee_families" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "employee_id" bigint [not null]
  "name" varchar(255) [not null]
  "relationship" relationship_enum [default: NULL]
  "address" varchar(255) [NULL]
  "id_number" varchar(16) [not null]
  "gender" varchar(10) [default: NULL]
  "date_of_birth" date [default: NULL]
  "religion" varchar(255) [not null]
  "martial_status" varchar(255) [NOT NULL]
  "job" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_id [name: "employee_families_employee_id_foreign"]
  }
}

Table "employee_task_points" {
  "id" bigint [pk, not null, increment]
  "employee_id" int [not null]
  "point" double [not null]
  "additional_point" double [not null, default: '0']
  "total_point" double [not null, default: '0']
  "total_task" double [not null, default: '0']
  "project_id" int [not null]
  "created_by" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

// This table is used with NEW WORKFLOW. WILL IMPLEMENT ON ENTERTAINMENT POINT FIRST.
// TODO: Pointing production point to this table
Table "employee_points" {
  "id" bigint [pk, not null, increment]
  "employee_id" bigint [not null]
  "point" integer [default: 0]
  "additional_point" integer [default: 0]
  "project_id" bigint [not null]
  "task_type" employee_points_task_type
  "task_id" varchar(255) [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

// REFACTORED EMPLOYEE POINTS
Table "employee_points" {
  "id" bigint [pk, not null, increment]
  "employee_id" bigint [not null, ref: > employees.id]
  "total_point" integer [not null, default: 0]
  "type" enum [note: "entertainment,production"]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "employee_point_projects" {
  "id" bigint [pk, not null, increment]
  "employee_point_id" bigint [not null]
  "project_id" bigint [not null]
  "total_point" integer [not null]
  "additional_point" integer [not null, default: 0]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "employee_point_project_details" {
  "id" bigint [pk, not null, increment]
  "point_id" bigint [not null]
  "task_id" bigint [not null]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "employees" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "nickname" varchar(255) [default: NULL]
  "email" varchar(255) [not null]
  "date_of_birth" date [not null]
  "place_of_birth" varchar(255) [not null]
  "martial_status" employees_martial_status_enum [not null]
  "religion" employees_religion_enum [not null]
  "phone" varchar(15) [not null]
  "id_number" varchar(16) [not null]
  "address" varchar(255) [not null]
  "current_address" varchar(255) [default: NULL]
  "position_id" bigint [not null]
  "employee_id" varchar(150) [not null]
  "level_staff" employees_level_staff_enum [not null]
  "boss_id" int [default: NULL]
  "status" tinyint [not null, note: '1 for permanenet, 2 for contract, 3 for part time, 4 for freelance, 5 for internship, 6 for inactive, 7 for waiting HR checking (usually comes from self-filling after the contract)']
  "branch_id" bigint [not null]
  "join_date" date [not null]
  "gender" employees_gender_enum [not null]

  // new
  "ptkp_status" varchar(5) [not null]
  "basic_salry" decimal [not null, default: 0]
  "salary_type" salaray_type_enum [not null]

  "bpjs_ketenagakerjaan_number" varchar(50) [default: NULL]
  "npwp_number" varchar(50) [default: NULL]

  "province_id" int [default: NULL]
  "city_id" int [default: NULL]
  "district_id" bigint [default: NULL]
  "village_id" bigint [default: NULL]
  "postal_code" varchar(6) [not null]
  "blood_type" varchar(2) [default: NULL]
  "bank_detail" json [default: NULL, note: 'Format: [{"bank_name": "", "account_number": "", "account_holder_name": "", "is_active": ""}]']
  "education" employees_education_enum [not null]
  "education_name" varchar(255) [default: NULL]
  "education_major" varchar(255) [default: NULL]
  "education_year" year [default: NULL]
  "relation_contact" json [default: NULL, note: 'Format: {"name": "", "phone": "", "relationship": ""}']
  "start_review_probation_date" date [default: NULL]
  "end_probation_date" date [default: NULL]
  "probation_status" tinyint [default: NULL]
  "bpjs_status" tinyint [default: NULL]
  "bpjs_kesehatan_number" varchar(50) [default: NULL]
  "bpjs_photo" varchar(255) [default: NULL]
  "npwp_photo" varchar(255) [default: NULL]
  "id_number_photo" varchar(255) [default: NULL]
  "kk_photo" varchar(255) [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "deleted_at" timestamp [default: NULL]
  "user_id" int [default: NULL]
  "line_id" varchar(255) [default: NULL]
  "end_date" date [default: NULL]
  "resign_reason" varchar(255) [default: NULL]
  "telegram_chat_id" varchar(255) [default: NULL]

  // deleted
  "dependant" varchar(10) [default: NULL, note: 'tanggungan']
  "placement" varchar(255) [default: NULL]
  "company_name" varchar(255) [default: NULL]

  Indexes {
    position_id [name: "employees_position_id_foreign"]
  }
}

Table "failed_jobs" {
  "id" bigint [pk, not null, increment]
  "uuid" varchar(255) [not null]
  "connection" text [not null]
  "queue" text [not null]
  "payload" longtext [not null]
  "exception" longtext [not null]
  "failed_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    uuid [unique, name: "failed_jobs_uuid_unique"]
  }
}

Table "form_interactive_responses" {
  "id" bigint [pk, not null, increment]
  "form_interactive_id" int [not null]
  "response" json [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "form_interactives" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "forms" json [not null]
  "qrcode" varchar(255) [default: NULL]
  "background" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "indonesia_cities" {
  "code" char(4) [pk, not null]
  "province_code" char(2) [not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]

  Indexes {
    province_code [name: "indonesia_cities_province_code_foreign"]
  }
}

Table "indonesia_districts" {
  "code" char(7) [pk, not null]
  "city_code" char(4) [not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]

  Indexes {
    city_code [name: "indonesia_districts_city_code_foreign"]
  }
}

Table "indonesia_provinces" {
  "code" char(2) [pk, not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]
}

Table "indonesia_villages" {
  "code" char(10) [pk, not null]
  "district_code" char(7) [not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]
  "postal_code" varchar(255) [default: NULL]

  Indexes {
    district_code [name: "indonesia_villages_district_code_foreign"]
  }
}

Table "inventories" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "stock" double [not null, default: '0']
  "item_type" int [not null]
  "brand_id" int [not null]
  "supplier_id" int [default: NULL]
  "unit_id" int [default: NULL]
  "description" text
  "warranty" tinyint [default: NULL, note: 'in years']
  "year_of_purchase" year [default: NULL]
  "purchase_price" double [not null, default: '0']
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "warehouse_id" tinyint [default: NULL, note: 'Static id. 1 for office, 2 for entertaint']
}

Table "inventory_images" {
  "id" bigint [pk, not null, increment]
  "inventory_id" bigint [not null]
  "image" varchar(255) [not null]
  "is_main" tinyint(1) [not null, default: '0']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    inventory_id [name: "inventory_images_inventory_id_foreign"]
  }
}

Table "inventory_items" {
  "id" bigint [pk, not null, increment]
  "inventory_id" bigint [not null]
  "inventory_code" varchar(50) [not null]
  "status" tinyint [not null, note: '1 for in use, 2 for in repair, 3 for broke, 4 for disposal']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "current_location" tinyint [default: NULL, note: '1 for in user, 2 for in warehouse, 3 for in outside']
  "user_id" int [default: NULL]
  "qrcode" varchar(255) [default: NULL]
  "purchase_price" double [not null]
  "warranty" int [default: NULL]
  "year_of_purchase" year [default: NULL]

  Indexes {
    inventory_id [name: "inventory_items_inventory_id_foreign"]
  }
}

Table "employee_inventory_masters" {
    "id" bigint [pk, not null, increment]
    "employee_id" bigint [not null]
    inventory_item_id bigint [not null]
}

Table "inventory_maintenance_requests" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_position_histories" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_positions" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_request_items" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_requests" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_types" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "slug" varchar(20) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "job_batches" {
  "id" varchar(255) [pk, not null]
  "name" varchar(255) [not null]
  "total_jobs" int [not null]
  "pending_jobs" int [not null]
  "failed_jobs" int [not null]
  "failed_job_ids" longtext [not null]
  "options" mediumtext
  "cancelled_at" int [default: NULL]
  "created_at" int [not null]
  "finished_at" int [default: NULL]
}

Table "jobs" {
  "id" bigint [pk, not null, increment]
  "queue" varchar(255) [not null]
  "payload" longtext [not null]
  "attempts" tinyint [not null]
  "reserved_at" int [default: NULL]
  "available_at" int [not null]
  "created_at" int [not null]

  Indexes {
    queue [name: "jobs_queue_index"]
  }
}

Table "line_messages" {
  "id" bigint [pk, not null, increment]
  "type" varchar(255) [default: NULL]
  "user_id" varchar(255) [default: NULL]
  "message" json [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "menus" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "parent_id" int [default: NULL]
  "icon" varchar(255) [default: NULL]
  "link" varchar(255) [default: NULL]
  "permission" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "group" tinyint [not null]
  "lang_id" varchar(255) [default: NULL]
  "lang_en" varchar(255) [default: NULL]
  "app_type" varchar(100) [default: 'old', note: 'as a marker whether the menu is displayed in the application with the old or new design. if office then new, other than that is the old display']
  "new_icon" varchar(255) [default: NULL]
  "new_link" varchar(255) [default: NULL]
}

Table "migrations" {
  "id" int [pk, not null, increment]
  "migration" varchar(255) [not null]
  "batch" int [not null]
}

Table "model_has_permissions" {
  "permission_id" bigint [not null]
  "model_type" varchar(255) [not null]
  "model_id" bigint [not null]

  Indexes {
    (permission_id, model_id, model_type) [pk]
    (model_id, model_type) [name: "model_has_permissions_model_id_model_type_index"]
  }
}

Table "model_has_roles" {
  "role_id" bigint [not null]
  "model_type" varchar(255) [not null]
  "model_id" bigint [not null]

  Indexes {
    (role_id, model_id, model_type) [pk]
    (model_id, model_type) [name: "model_has_roles_model_id_model_type_index"]
  }
}

Table "notification_templates" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "notifications" {
  "id" char(36) [pk, not null]
  "type" varchar(255) [not null]
  "notifiable_type" varchar(255) [not null]
  "notifiable_id" bigint [not null]
  "data" text [not null]
  "read_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    (notifiable_type, notifiable_id) [name: "notifications_notifiable_type_notifiable_id_index"]
  }
}

Table "password_reset_tokens" {
  "email" varchar(255) [pk, not null]
  "token" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
}

Table "permissions" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "guard_name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "group" varchar(255) [default: NULL]

  Indexes {
    (name, guard_name) [unique, name: "permissions_name_guard_name_unique"]
  }
}

Table "personal_access_tokens" {
  "id" bigint [pk, not null, increment]
  "tokenable_type" varchar(255) [not null]
  "tokenable_id" bigint [not null]
  "name" varchar(255) [not null]
  "token" varchar(64) [not null]
  "abilities" text
  "last_used_at" timestamp [default: NULL]
  "expires_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    token [unique, name: "personal_access_tokens_token_unique"]
    (tokenable_type, tokenable_id) [name: "personal_access_tokens_tokenable_type_tokenable_id_index"]
  }
}

Table "positions" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "division_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]

  Indexes {
    division_id [name: "positions_division_id_foreign"]
  }
}

Table "project_boards" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "name" varchar(255) [not null]
  "sort" varchar(2) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "based_board_id" int [default: NULL]

  Indexes {
    project_id [name: "project_boards_project_id_foreign"]
  }
}

Table "project_classes" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "maximal_point" tinyint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "color" varchar(20) [default: NULL]
}

Table "project_equipment" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_id" bigint [not null]
  "inventory_id" int [not null]
  "qty" int [not null]
  "status" tinyint [not null, note: '1 for ready, 2 for requested, 3 for decline']
  "project_date" date [not null]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "is_checked_pic" tinyint(1) [not null, default: '0']
  "inventory_code" varchar(30) [default: NULL]
  "is_good_condition" tinyint(1) [default: NULL]
  "detail_condition" varchar(255) [default: NULL]
  "is_returned" tinyint(1) [default: NULL]

  Indexes {
    project_id [name: "project_equipment_project_id_foreign"]
  }
}

Table "project_marketings" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "marketing_id" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "project_marketings_project_id_foreign"]
  }
}

Table "project_person_in_charges" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "pic_id" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "project_person_in_charges_project_id_foreign"]
  }
}

Table "project_references" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "media_path" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "name" varchar(255) [default: NULL]
  "type" varchar(100) [default: NULL]
  "folder" varchar(150) [default: NULL]

  Indexes {
    project_id [name: "project_references_project_id_foreign"]
  }
}

Table "project_task_attachments" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "project_id" bigint [not null]
  "media" varchar(255) [default: NULL]
  "display_name" varchar(255) [default: NULL]
  "related_task_id" int [default: NULL]
  "type" tinyint [not null, note: '1 for media, 2 for other task link, 3 for external link']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_attachments_project_task_id_foreign"]
    project_id [name: "project_task_attachments_project_id_foreign"]
  }
}

Table "project_task_logs" {
  "id" bigint [pk, not null, increment]
  "project_task_id" int [default: NULL]
  "type" varchar(255) [default: NULL]
  "text" varchar(255) [default: NULL]
  "user_id" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_task_pic_histories" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "project_task_id" bigint [not null]
  "employee_id" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "project_task_pic_histories_project_id_foreign"]
    project_task_id [name: "project_task_pic_histories_project_task_id_foreign"]
  }
}

Table "project_task_pic_logs" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "employee_id" int [not null]
  "work_type" varchar(30) [not null, note: 'will be: assigned, on_progress, check_by_pm, revise, finish']
  "time_added" timestamp [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_pic_logs_project_task_id_foreign"]
  }
}

Table "project_task_pics" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "status" varchar(1) [default: NULL]
  "assigned_at" timestamp [default: NULL]
  "approved_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_pics_project_task_id_foreign"]
    employee_id [name: "project_task_pics_employee_id_foreign"]
  }
}

Table "project_task_proof_of_works" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "project_id" int [not null]
  "nas_link" varchar(255) [default: NULL]
  "preview_image" json [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_year" year [default: NULL]
  "created_month" tinyint [default: NULL]

  Indexes {
    project_task_id [name: "project_task_proof_of_works_project_task_id_foreign"]
  }
}

Table "project_task_revise_histories" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "project_id" int [default: NULL]
  "selected_user" json [default: NULL, note: 'who is working on this revise task']
  "reason" varchar(255) [default: NULL]
  "file" varchar(255) [default: NULL]
  "revise_by" int [default: NULL, note: 'who is create this revise reason (base on employee id)']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_revise_histories_project_task_id_foreign"]
  }
}

Table "project_task_worktimes" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "employee_id" int [default: NULL]
  "user_id" int [default: NULL]
  "project_id" int [default: NULL]
  "start_at" timestamp [default: NULL]
  "end_at" timestamp [default: NULL]
  "work_type" project_task_worktimes_work_type_enum [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_worktimes_project_task_id_foreign"]
  }
}

Table "project_tasks" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "task_identifier_id" varchar(4) [unique, note: "used as relation key with HR data"]
  "project_id" bigint [not null]
  "project_board_id" bigint [not null]
  "start_date" date [default: NULL]
  "end_date" date [default: NULL]
  "description" text
  "name" varchar(255) [not null]
  "start_working_at" datetime [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "task_type" project_tasks_task_type_enum [default: NULL]
  "performance_time" json [default: NULL, note: '''will be [{type: \'\'on_progress\'\', start_at: \'\'2024-05-24 20:00:00\'\', end_at: \'\'\'\'}]. and will be have type: on_progress, review_by_pm, review_by_client''']
  "status" tinyint [default: NULL, note: '1 for on process, 2 for check by pm, 3 for revise, 4 for completed']
  "current_pics" json [default: NULL, note: 'This column will be update in every task movement. Format will be array of id like [1,2,3]']
  "current_board" int [default: NULL]
  "is_approved" tinyint [not null, default: '0']

  Indexes {
    project_id [name: "project_tasks_project_id_foreign"]
    project_board_id [name: "project_tasks_project_board_id_foreign"]
  }
}

Table "project_vjs" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_by" int [not null]

  Indexes {
    project_id [name: "project_vjs_project_id_foreign"]
    employee_id [name: "project_vjs_employee_id_foreign"]
  }
}

Table "projects" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "client_portal" varchar(255) [not null]
  "project_date" date [not null]
  "event_type" projects_event_type_enum [default: NULL]
  "venue" varchar(255) [not null]
  "marketing_id" int [default: NULL]
  "collaboration" varchar(255) [default: NULL]
  "note" text
  "status" tinyint [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "led_area" double [not null, default: '0']
  "led_detail" json [default: NULL]
  "uid" char(36) [not null]
  "showreels" varchar(255) [default: NULL]
  "country_id" int [default: NULL]
  "state_id" int [default: NULL]
  "city_id" int [default: NULL]
  "city_name" varchar(255) [default: NULL]
  "project_class_id" int [default: NULL]
  "classification" varchar(255) [default: NULL]
  "showreels_status" tinyint [default: NULL]
  "longitude" varchar(150) [default: NULL]
  "latitude" varchar(150) [default: NULL]
  "feedback" text
}

Table "project_song_lists" {
  "id" bigint [pk, not null, increment]
  "uid" char(16) [not null]
  "project_id" bigint [not null]
  "name" varchar(255) [not null]
  "is_request_edit" tinyint(1) [default: '0']
  "is_request_delete" tinyint(1) [default: '0']
  "created_at" timestamp
  "created_by" bigint
  "updated_at" timestamp
}

Table "entertainment_task_songs" {
  "id" bigint [pk, not null, increment]
  "project_song_list_id" bigint [not null]
  "status" enum
  "employee_id" bigint [not null]
  "time_tracker" longtext [note: "will be like: [{type: 'start_working', start_time: '2025-01-10 10:00', 'end_time': null}]. Type will be start_working, start_revise"]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "entertainment_task_song_revises" {
  "id" bigint [pk, increment]
  "project_song_list_id" bigint [not null]
  "entertainment_task_song_id" bigint [not null]
  "reason" varchar [not null]
  "images" longtext
  "created_at" timestamp
  "updated_at" timestamp
}

Table "entertainment_task_song_results" {
  "id" bigint [pk, not null, increment]
  "entertainment_task_song_id" bigint [not null]
  "nas_path" varchar(255) [not null]
  "employee_id" bigint [not null]
  "note" text
  "created_at" timestamp
  "updated_at" timestamp
}

Table "entertainment_task_song_result_images" {
  "id" bigint [pk, not null, increment]
  "entertainment_task_song_result_id" bigint
  "path" varchar(255)
  "created_at" timestamp
  "updated_at" timestamp
}



Table "request_inventories" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "description" text
  "price" double [not null, default: '0']
  "quantity" tinyint [not null, default: '0']
  "purchase_source" varchar(255) [default: NULL]
  "purchase_link" json [default: NULL]
  "status" tinyint [not null, default: '1', note: '1 for requested, 2 for approved, 3 for rejected']
  "requested_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "approval_target" json [default: NULL]
  "store_name" varchar(255) [default: NULL]
  "approved_by" int [default: NULL]
  "rejected_by" int [default: NULL]
}

Table "role_has_permissions" {
  "permission_id" bigint [not null]
  "role_id" bigint [not null]

  Indexes {
    (permission_id, role_id) [pk]
    role_id [name: "role_has_permissions_role_id_foreign"]
  }
}

Table "roles" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "guard_name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    (name, guard_name) [unique, name: "roles_name_guard_name_unique"]
  }
}

Table "sessions" {
  "id" varchar(255) [pk, not null]
  "user_id" bigint [default: NULL]
  "ip_address" varchar(45) [default: NULL]
  "user_agent" text
  "payload" longtext [not null]
  "last_activity" int [not null]

  Indexes {
    user_id [name: "sessions_user_id_index"]
    last_activity [name: "sessions_last_activity_index"]
  }
}

Table "settings" {
  "id" bigint [pk, not null, increment]
  "key" varchar(255) [default: NULL]
  "value" longtext
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "code" varchar(255) [default: NULL]
}

Table "states" {
  "id" bigint [pk, not null, increment]
  "country_id" bigint [not null]
  "name" varchar(255) [not null]
  "country_code" varchar(3) [default: NULL]
}

Table "suppliers" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
}

Table "telegram_chat_commands" {
  "id" bigint [pk, not null, increment]
  "chat_id" varchar(255) [not null]
  "command" varchar(255) [not null]
  "status" tinyint(1) [not null, default: '1']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "current_function" varchar(255) [default: NULL]
}

Table "telegram_chat_histories" {
  "id" bigint [pk, not null, increment]
  "chat_id" varchar(255) [not null]
  "message" text [not null]
  "message_id" varchar(255) [default: NULL]
  "status" tinyint [not null, default: '1', note: '1 for processing, 2 for success, 3 for failed']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "chat_type" varchar(255) [default: NULL]
  "bot_command" varchar(255) [default: NULL]
  "from_customer" tinyint(1) [not null, default: '0']
  "is_closed" tinyint(1) [not null, default: '0']
  "topic" varchar(255) [default: NULL]
}

Table "telegram_report_tasks" {
  "id" bigint [pk, not null, increment]
  "task_id" int [default: NULL]
  "telegram_chat_id" varchar(255) [default: NULL]
  "nas_link" varchar(255) [default: NULL]
  "file_id" varchar(255) [default: NULL]
  "mime_type" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "telegram_transactions" {
  "id" bigint [pk, not null, increment]
  "chat_id" varchar(255) [not null]
  "message_id" varchar(255) [not null]
  "identity" varchar(255) [not null]
  "status" tinyint(1) [not null, default: '1']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "telescope_entries" {
  "sequence" bigint [pk, not null, increment]
  "uuid" char(36) [not null]
  "batch_id" char(36) [not null]
  "family_hash" varchar(255) [default: NULL]
  "should_display_on_index" tinyint(1) [not null, default: '1']
  "type" varchar(20) [not null]
  "content" longtext [not null]
  "created_at" datetime [default: NULL]

  Indexes {
    uuid [unique, name: "telescope_entries_uuid_unique"]
    batch_id [name: "telescope_entries_batch_id_index"]
    family_hash [name: "telescope_entries_family_hash_index"]
    created_at [name: "telescope_entries_created_at_index"]
    (type, should_display_on_index) [name: "telescope_entries_type_should_display_on_index_index"]
  }
}

Table "telescope_entries_tags" {
  "entry_uuid" char(36) [not null]
  "tag" varchar(255) [not null]

  Indexes {
    (entry_uuid, tag) [pk]
    tag [name: "telescope_entries_tags_tag_index"]
  }
}

Table "telescope_monitoring" {
  "tag" varchar(255) [pk, not null]
}

Table "transfer_team_members" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_id" bigint [not null]
  "employee_id" int [default: NULL]
  "request_to" int [not null]
  "reason" varchar(255) [not null]
  "project_date" date [not null]
  "request_at" timestamp [default: NULL]
  "approved_at" timestamp [default: NULL]
  "completed_at" timestamp [default: NULL]
  "rejected_at" timestamp [default: NULL]
  "canceled_at" timestamp [default: NULL]
  "reject_reason" varchar(255) [default: NULL]
  "device_action" varchar(10) [default: NULL, note: 'device resource for any action take. It should line or web']
  "status" tinyint [not null, note: '1 for requested, 2 for approved, 3 for reject, 4 completed']
  "requested_by" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "alternative_employee_id" int [default: NULL]
  "is_entertainment" tinyint(1) [not null, default: '0']

  Indexes {
    project_id [name: "transfer_team_members_project_id_foreign"]
  }
}

Table "units" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "user_encrypted_tokens" {
  "id" bigint [pk, not null, increment]
  "user_id" int [not null]
  "data" longtext [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "user_login_histories" {
  "id" bigint [pk, not null, increment]
  "user_id" int [not null]
  "login_at" timestamp [not null]
  "ip" varchar(100) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "browser" varchar(200) [default: NULL]
}

Table "users" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "email" varchar(255) [not null]
  "email_verified_at" timestamp [default: NULL]
  "password" varchar(255) [not null]
  "image" varchar(255) [default: NULL]
  "last_login_at" timestamp [default: NULL]
  "remember_token" varchar(100) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "is_external_user" tinyint(1) [not null, default: '0']
  "username" varchar(255) [default: NULL]
  "employee_id" int [default: NULL]
  "is_employee" tinyint(1) [default: NULL]
  "is_project_manager" tinyint(1) [default: NULL]
  "is_director" tinyint(1) [default: NULL]
  "reset_password_token_exp" timestamp [default: NULL]
  "reset_password_token_claim" tinyint(1) [default: NULL]
  "name" varchar(255) [default: NULL, note: 'come from filament resource']

  Indexes {
    email [unique, name: "users_email_unique"]
  }
}

Table "nas_folder_creations" {
  "id" bigint [pk, not null, increment]
  "project_name" varchar(255) [not null]
  "project_id" bigint [not null]
  "folder_path" longtext [not null, note: '["2024/01_Januari_Event_Name/Brief", "2024/01_Januari_Event_Name/Asset_3D", "2024/01_Januari_Event_Name/Asset_Footage"]']
  "status" bool [default: 1]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "nas_folder_creation_backups" {
  "id" bigint [pk, not null, increment]
  "shared_folder" varchar [not null]
  "year" year [not null]
  "month_name" varchar [not null]
  "project_name" varchar [not null]
  "prefix_project_name" varchar [not null]
  "child_folders" longtext [not null]
  "project_id" bigint [not null]
  "status" tinyint [default: 1 note: '0 is complete, 1 is ready, 2 is onging, 3 is failed']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_logs" {
    "id" bigint [pk, not null, increment]
    "project_id" bigint [not null]
    "message" varchar(255) [not null]
    "created_at" timestamp [default: NULL]
    "updated_at" timestamp [default: NULL]
}

Table "branches" {
  "id" bigint [pk, increment, not null]
  "name" varchar(255) [not null]
  "short_name" varchar(50) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "interactive_images" {
  "id" bigint [pk, increment, not null]
  "qrcode" varchar(255) [not null]
  "filepath" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "employees"."branch_id" < "branches"."id"

Ref: "project_logs"."project_id" < "projects.id"

Ref: "nas_folder_creation"."project_id" < "projects"."id"

Ref "custom_inventory_details_custom_inventory_id_foreign":"custom_inventories"."id" < "custom_inventory_details"."custom_inventory_id" [delete: cascade]

Ref "custom_inventory_details_ibfk_1":"inventory_items"."id" < "custom_inventory_details"."inventory_id"

Ref "employee_emergency_contacts_employee_id_foreign":"employees"."id" < "employee_emergency_contacts"."employee_id" [delete: cascade]

Ref "employee_families_employee_id_foreign":"employees"."id" < "employee_families"."employee_id" [delete: cascade]

Ref "employees_position_id_foreign":"positions"."id" < "employees"."position_id"

Ref "indonesia_cities_province_code_foreign":"indonesia_provinces"."code" < "indonesia_cities"."province_code" [update: cascade, delete: restrict]

Ref "indonesia_districts_city_code_foreign":"indonesia_cities"."code" < "indonesia_districts"."city_code" [update: cascade, delete: restrict]

Ref "indonesia_villages_district_code_foreign":"indonesia_districts"."code" < "indonesia_villages"."district_code" [update: cascade, delete: restrict]

Ref "inventory_images_inventory_id_foreign":"inventories"."id" < "inventory_images"."inventory_id" [delete: cascade]

Ref "inventory_items_inventory_id_foreign":"inventories"."id" < "inventory_items"."inventory_id" [delete: cascade]

Ref "model_has_permissions_permission_id_foreign":"permissions"."id" < "model_has_permissions"."permission_id" [delete: cascade]

Ref "model_has_roles_role_id_foreign":"roles"."id" < "model_has_roles"."role_id" [delete: cascade]

Ref "positions_division_id_foreign":"divisions"."id" < "positions"."division_id" [delete: cascade]

Ref "project_boards_project_id_foreign":"projects"."id" < "project_boards"."project_id" [delete: cascade]

Ref "project_equipment_project_id_foreign":"projects"."id" < "project_equipment"."project_id" [delete: cascade]

Ref "project_marketings_project_id_foreign":"projects"."id" < "project_marketings"."project_id" [delete: cascade]

Ref "project_person_in_charges_project_id_foreign":"projects"."id" < "project_person_in_charges"."project_id"

Ref "project_references_project_id_foreign":"projects"."id" < "project_references"."project_id" [delete: cascade]

Ref "project_task_attachments_project_id_foreign":"projects"."id" < "project_task_attachments"."project_id" [delete: cascade]

Ref "project_task_attachments_project_task_id_foreign":"project_tasks"."id" < "project_task_attachments"."project_task_id" [delete: cascade]

Ref "project_task_pic_histories_project_id_foreign":"projects"."id" < "project_task_pic_histories"."project_id" [delete: cascade]

Ref "project_task_pic_histories_project_task_id_foreign":"project_tasks"."id" < "project_task_pic_histories"."project_task_id" [delete: cascade]

Ref "project_task_pic_logs_project_task_id_foreign":"project_tasks"."id" < "project_task_pic_logs"."project_task_id" [delete: cascade]

Ref "project_task_pics_employee_id_foreign":"employees"."id" < "project_task_pics"."employee_id" [delete: cascade]

Ref "project_task_pics_project_task_id_foreign":"project_tasks"."id" < "project_task_pics"."project_task_id" [delete: cascade]

Ref "project_task_proof_of_works_project_task_id_foreign":"project_tasks"."id" < "project_task_proof_of_works"."project_task_id" [delete: cascade]

Ref "project_task_revise_histories_project_task_id_foreign":"project_tasks"."id" < "project_task_revise_histories"."project_task_id" [delete: cascade]

Ref "project_task_worktimes_project_task_id_foreign":"project_tasks"."id" < "project_task_worktimes"."project_task_id" [delete: cascade]

Ref "project_tasks_project_board_id_foreign":"project_boards"."id" < "project_tasks"."project_board_id" [delete: cascade]

Ref "project_tasks_project_id_foreign":"projects"."id" < "project_tasks"."project_id" [delete: cascade]

Ref "project_vjs_employee_id_foreign":"employees"."id" < "project_vjs"."employee_id" [delete: cascade]

Ref "project_vjs_project_id_foreign":"projects"."id" < "project_vjs"."project_id" [delete: cascade]

Ref "role_has_permissions_permission_id_foreign":"permissions"."id" < "role_has_permissions"."permission_id" [delete: cascade]

Ref "role_has_permissions_role_id_foreign":"roles"."id" < "role_has_permissions"."role_id" [delete: cascade]

Ref "telescope_entries_tags_entry_uuid_foreign":"telescope_entries"."uuid" < "telescope_entries_tags"."entry_uuid" [delete: cascade]

Ref "transfer_team_members_project_id_foreign":"projects"."id" < "transfer_team_members"."project_id" [delete: cascade]

Ref "user_inventories_inventory_id_foreign":"inventory_items"."id" < "user_inventories"."inventory_id" [delete: cascade]

Ref "user_inventories_user_inventory_master_id_foreign":"user_inventory_masters"."id" < "user_inventories"."user_inventory_master_id" [delete: cascade]

Ref "user_inventory_masters_employee_id_foreign":"employees"."id" < "user_inventory_masters"."employee_id" [delete: cascade]
