
Enum "employee_families_relationship_enum" {
  "father"
  "mother"
  "sibling"
  "child"
  "other"
}

Enum "project_deal_changes_status" {
  "1", // for pending
  "2", // for approved
  "3" // for rejected
}

Enum "project_task_duration_history_enums" {
  "cross_team_collaboration"
  "single_assignee"
  "temporary_transfer"
  "split_assignment"
}

Enum "invoice_statuses" {
  "1", // unpaid
  "2", // paid
}

Enum "transaction_enum" {
  "down_payment",
  "credit",
  "repayment"
}

Enum "project_task_deadline_type" {
  "revise"
  "general"
}

Enum "project_deal_equipment_type" {
  "lasika"
  "others"
}

Enum "employee_inventory_items_inventory_source_enum" {
  "custom"
  "inventory"
}

Enum "employee_point_details_type_enum" {
  "entertainment"
  "production"
}

Enum "employee_points_type_enum" {
  "production"
  "entertainment"
}

Enum "employees_religion_enum" {
  "katholik"
  "islam"
  "kristen"
  "budha"
  "hindu"
  "konghucu"
}

Enum "employees_martial_status_enum" {
  "married"
  "single"
}

Enum "employees_gender_enum" {
  "female"
  "male"
}

Enum "employees_education_enum" {
  "smp"
  "sma"
  "smk"
  "diploma"
  "s1"
  "s2"
  "s3"
}

Enum "event_equipments_type_enum" {
  "mixed"
  "regular"
  "custom"
}

Enum "nas_folder_creations_type_enum" {
  "create"
  "update"
  "delete"
}

Enum "project_task_worktimes_work_type_enum" {
  "on_progress"
  "review_by_pm"
  "review_by_client"
}

Enum "project_tasks_task_type_enum" {
  "asset3d"
  "compositing"
  "animating"
  "finalize"
}

Enum "projects_event_type_enum" {
  "wedding"
  "engagement"
  "event"
  "birthday"
  "concert"
  "corporate"
  "exhibition"
}

Table "addon_update_histories" {
  "id" bigint [pk, not null, increment]
  "addon_id" int [not null]
  "improvements" longtext [not null]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "addons" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "description" text
  "preview_img" varchar(255) [not null]
  "tutorial_video" varchar(255) [default: NULL]
  "main_file" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "banks" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "bank_code" tinyint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "branches" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "short_name" varchar(50) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "brands" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
}

Table "cache" {
  "key" varchar(255) [pk, not null]
  "value" mediumtext [not null]
  "expiration" int [not null]
}

Table "cache_locks" {
  "key" varchar(255) [pk, not null]
  "owner" varchar(255) [not null]
  "expiration" int [not null]
}

Table "cities" {
  "id" bigint [pk, not null, increment]
  "country_id" bigint [not null]
  "state_id" bigint [not null]
  "name" varchar(255) [not null]
  "country_code" varchar(255) [not null]
}

Table "countries" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "iso3" varchar(255) [not null]
  "iso2" varchar(255) [not null]
  "phone_code" varchar(255) [not null]
  "currency" varchar(255) [not null]
}

Table "custom_inventories" {
  "id" bigint [pk, not null, increment]
  "barcode" varchar(255) [default: NULL]
  "uid" char(36) [not null]
  "build_series" varchar(255) [not null]
  "name" varchar(255) [not null]
  "type" varchar(255) [not null]
  "location" tinyint [not null]
  "default_request_item" tinyint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "custom_inventory_details" {
  "id" bigint [pk, not null, increment]
  "custom_inventory_id" bigint [not null]
  "inventory_id" bigint [not null]
  "qty" int [not null]
  "price" double [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    custom_inventory_id [name: "custom_inventory_details_custom_inventory_id_foreign"]
    inventory_id [name: "custom_inventory_details_inventory_id_foreign"]
  }
}

Table "customers" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "phone" varchar(20) [not null]
  "email" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "division_backups" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "parent_id" int [default: NULL]
  "uid" char(36) [not null]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "divisions" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "parent_id" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "uid" char(36) [default: NULL]
}

Table "document_templates" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "employee_active_reports" {
  "id" bigint [pk, not null, increment]
  "month" tinyint [not null]
  "year" year [not null]
  "number_of_employee" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "employee_custom_inventories" {
  "id" bigint [pk, not null, increment]
  "employee_id" bigint [not null]
  "custom_inventory_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_id [name: "employee_custom_inventories_employee_id_foreign"]
    custom_inventory_id [name: "employee_custom_inventories_custom_inventory_id_foreign"]
  }
}

Table "employee_emergency_contacts" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "phone" varchar(255) [not null]
  "relation" varchar(255) [not null]
  "uid" char(36) [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_id [name: "employee_emergency_contacts_employee_id_foreign"]
  }
}

Table "employee_families" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "employee_id" bigint [not null]
  "name" varchar(255) [not null]
  "date_of_birth" date [default: NULL]
  "id_number" varchar(16) [default: NULL]
  "gender" varchar(10) [default: NULL]
  "job" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "relationship" employee_families_relationship_enum [not null]
  "address" varchar(255) [default: NULL]
  "religion" varchar(255) [default: NULL]
  "martial_status" varchar(255) [default: NULL]

  Indexes {
    employee_id [name: "employee_families_employee_id_foreign"]
  }
}

Table "employee_inventory_items" {
  "id" bigint [pk, not null, increment]
  "employee_inventory_master_id" bigint [not null]
  "inventory_item_id" bigint [not null]
  "inventory_status" bigint [not null, default: '1', note: '1 for active, 2 for disable']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "inventory_source" employee_inventory_items_inventory_source_enum [not null]
  "inventory_source_id" int [not null, default: '0']

  Indexes {
    employee_inventory_master_id [name: "employee_inventory_items_employee_inventory_master_id_foreign"]
    inventory_item_id [name: "employee_inventory_items_inventory_item_id_foreign"]
  }
}

Table "employee_inventory_masters" {
  "id" bigint [pk, not null, increment]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "custom_inventory_id" longtext

  Indexes {
    employee_id [name: "employee_inventory_masters_employee_id_foreign"]
  }
}

Table "employee_point_details" {
  "id" bigint [pk, not null, increment]
  "employee_point_id" bigint [not null]
  "task_id" bigint [not null]
  "point" int [not null]
  "type" employee_point_details_type_enum [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_point_id [name: "employee_point_details_employee_point_id_foreign"]
  }
}

Table "employee_point_project_details" {
  "id" bigint [pk, not null, increment]
  "point_id" bigint [not null]
  "task_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    point_id [name: "employee_point_project_details_point_id_foreign"]
  }
}

Table "employee_point_projects" {
  "id" bigint [pk, not null, increment]
  "employee_point_id" bigint [not null]
  "project_id" bigint [not null]
  "total_point" int [not null, note: 'point + additional point']
  "additional_point" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_point_id [name: "employee_point_projects_employee_point_id_foreign"]
  }
}

Table "employee_points" {
  "id" bigint [pk, not null, increment]
  "employee_id" bigint [not null]
  "total_point" int [not null, note: 'This is a global total point for each employee']
  "type" employee_points_type_enum [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_id [name: "employee_points_employee_id_foreign"]
  }
}

Table "employee_resigns" {
  "id" bigint [pk, not null, increment]
  "employee_id" bigint [default: NULL]
  "reason" text [not null]
  "resign_date" date [not null]
  "severance" decimal(20,2) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_id [name: "employee_resigns_employee_id_foreign"]
  }
}

Table "employee_task_points" {
  "id" bigint [pk, not null, increment]
  "employee_id" int [not null]
  "point" double [not null]
  "additional_point" double [not null, default: '0']
  "total_point" double [not null, default: '0']
  "total_task" double [not null, default: '0']
  "project_id" int [not null]
  "created_by" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "employee_task_states" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "project_task_id" bigint [not null]
  "project_board_id" bigint [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "employee_timeoffs" {
  "id" bigint [pk, not null, increment]
  "time_off_id" bigint [not null, note: 'This data came from Talenta server']
  "talenta_user_id" bigint [default: NULL]
  "policy_name" varchar(255) [default: NULL, note: 'This data came from Talenta server']
  "request_type" varchar(100) [default: NULL, note: 'This data came from Talenta server']
  "file_url" varchar(255) [default: NULL, note: 'This data came from Talenta server']
  "start_date" date [default: NULL, note: 'This data came from Talenta server']
  "end_date" date [default: NULL, note: 'This data came from Talenta server']
  "status" varchar(100) [default: NULL, note: 'This data came from Talenta server']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "employees" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "nickname" varchar(255) [default: NULL]
  "email" varchar(255) [not null]
  "phone" varchar(15) [not null]
  "id_number" varchar(16) [not null]
  "religion" employees_religion_enum [not null]
  "martial_status" employees_martial_status_enum [not null]
  "address" varchar(255) [not null]
  "postal_code" varchar(6) [default: NULL]
  "current_address" varchar(255) [default: NULL]
  "blood_type" varchar(2) [default: NULL]
  "date_of_birth" date [not null]
  "place_of_birth" varchar(255) [default: NULL]
  "gender" employees_gender_enum [not null]
  "bank_detail" longtext [note: 'Format: [{"bank_name": "", "account_number": "", "account_holder_name": "", "is_active": ""}]']
  "relation_contact" longtext [note: 'Format: {"name": "", "phone": "", "relationship": ""}']
  "education" employees_education_enum [default: NULL]
  "education_name" varchar(255) [default: NULL]
  "education_major" varchar(255) [default: NULL]
  "education_year" year [default: NULL]
  "position_id" bigint [not null]
  "boss_id" int [default: NULL]
  "level_staff" varchar(255) [default: NULL]
  "status" tinyint [not null, note: '1 for permanenet, 2 for contract, 3 for part time, 4 for freelance, 5 for internship, 6 for inactive, 7 for waiting HR checking (usually comes from self-filling after the contract)']
  "join_date" date [not null]
  "start_review_probation_date" date [default: NULL]
  "probation_status" tinyint [default: NULL]
  "end_probation_date" date [default: NULL]
  "bpjs_status" tinyint [default: NULL]
  "bpjs_ketenagakerjaan_number" varchar(50) [default: NULL]
  "bpjs_kesehatan_number" varchar(50) [default: NULL]
  "npwp_number" varchar(50) [default: NULL]
  "bpjs_photo" varchar(255) [default: NULL]
  "npwp_photo" varchar(255) [default: NULL]
  "id_number_photo" varchar(255) [default: NULL]
  "kk_photo" varchar(255) [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "deleted_at" timestamp [default: NULL]
  "employee_id" varchar(150) [not null]
  "province_id" int [default: NULL]
  "city_id" int [default: NULL]
  "district_id" bigint [default: NULL]
  "village_id" bigint [default: NULL]
  "user_id" int [default: NULL]
  "line_id" varchar(255) [default: NULL]
  "end_date" date [default: NULL]
  "resign_reason" varchar(255) [default: NULL]
  "telegram_chat_id" varchar(255) [default: NULL]
  "branch_id" int [default: NULL]
  "ptkp_status" varchar(5) [default: NULL]
  "basic_salary" decimal(20,2) [not null, default: '0.00']
  "salary_type" tinyint [not null]
  "is_residence_same" tinyint(1) [not null, default: '0']
  "job_level_id" bigint [default: NULL]
  "is_sync_with_talenta" tinyint(1) [not null, default: '0']
  "avatar_color" varchar(255) [default: NULL]
  "talenta_user_id" varchar(100) [default: NULL]
  "tax_configuration" varchar(255) [default: NULL]
  "employee_tax_status" varchar(255) [default: NULL]
  "salary_configuration" varchar(255) [default: NULL]
  "jht_configuration" varchar(255) [default: NULL]
  "jp_configuration" varchar(255) [default: NULL]
  "overtime_status" varchar(255) [default: NULL]
  "bpjs_kesehatan_config" varchar(255) [default: NULL]

  Indexes {
    position_id [name: "employees_position_id_foreign"]
  }
}

Table "entertainment_task_song_logs" {
  "id" bigint [pk, not null, increment]
  "project_song_list_id" bigint [not null]
  "entertainment_task_song_id" bigint [not null, default: '0']
  "project_id" bigint [default: NULL]
  "text" varchar(255) [not null]
  "employee_id" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "param_text" longtext

  Indexes {
    project_song_list_id [name: "entertainment_task_song_logs_project_song_list_id_foreign"]
    entertainment_task_song_id [name: "entertainment_task_song_logs_entertainment_task_song_id_foreign"]
  }
}

Table "entertainment_task_song_result_images" {
  "id" bigint [pk, not null, increment]
  "result_id" bigint [not null]
  "path" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    result_id [name: "entertainment_task_song_result_images_result_id_foreign"]
  }
}

Table "entertainment_task_song_results" {
  "id" bigint [pk, not null, increment]
  "task_id" bigint [not null]
  "nas_path" varchar(255) [not null]
  "employee_id" bigint [not null]
  "note" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    task_id [name: "entertainment_task_song_results_task_id_foreign"]
  }
}

Table "entertainment_task_song_revises" {
  "id" bigint [pk, not null, increment]
  "project_song_list_id" bigint [not null]
  "entertainment_task_song_id" bigint [not null]
  "reason" varchar(255) [not null]
  "images" longtext
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "entertainment_task_songs" {
  "id" bigint [pk, not null, increment]
  "project_song_list_id" bigint [not null]
  "status" tinyint [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "project_id" bigint [not null]
  "time_tracker" longtext [note: '''will be like: [{type: \'\'start_working\'\', start_time: \'\'2025-01-10 10:00\'\', \'\'end_time\'\': null}]. Type will be start_working, start_revise''']

  Indexes {
    project_song_list_id [name: "entertainment_task_songs_project_song_list_id_foreign"]
    employee_id [name: "entertainment_task_songs_employee_id_foreign"]
    project_id [name: "entertainment_task_songs_project_id_foreign"]
  }
}

Table "event_equipment_details" {
  "id" bigint [pk, not null, increment]
  "event_equipment_id" bigint [not null]
  "inventory_item_id" bigint [not null]
  "custom_detail_id" bigint [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    event_equipment_id [name: "event_equipment_details_event_equipment_id_foreign"]
    inventory_item_id [name: "event_equipment_details_inventory_item_id_foreign"]
    custom_detail_id [name: "event_equipment_details_custom_detail_id_foreign"]
  }
}

Table "event_equipments" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "type" event_equipments_type_enum [not null]
  "requested_by" bigint [not null]
  "status" tinyint [not null, note: '1 for requested, 2 for processed']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "event_equipments_project_id_foreign"]
    requested_by [name: "event_equipments_requested_by_foreign"]
  }
}

Table "failed_jobs" {
  "id" bigint [pk, not null, increment]
  "uuid" varchar(255) [not null]
  "connection" text [not null]
  "queue" text [not null]
  "payload" longtext [not null]
  "exception" longtext [not null]
  "failed_at" timestamp [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    uuid [unique, name: "failed_jobs_uuid_unique"]
  }
}

Table "form_interactive_responses" {
  "id" bigint [pk, not null, increment]
  "form_interactive_id" int [not null]
  "response" longtext [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "form_interactives" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "forms" longtext [not null]
  "qrcode" varchar(255) [default: NULL]
  "background" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "indonesia_cities" {
  "code" char(4) [pk, not null]
  "province_code" varchar(10) [not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]

  Indexes {
    province_code [name: "indonesia_cities_province_code_foreign"]
  }
}

Table "indonesia_districts" {
  "code" char(7) [pk, not null]
  "city_code" char(4) [not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]

  Indexes {
    city_code [name: "indonesia_districts_city_code_foreign"]
  }
}

Table "indonesia_provinces" {
  "code" varchar(10) [pk, not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]
}

Table "indonesia_villages" {
  "code" char(10) [pk, not null]
  "district_code" char(7) [not null]
  "name" varchar(255) [not null]
  "latitude" varchar(255) [default: NULL]
  "longitude" varchar(255) [default: NULL]
  "postal_code" varchar(255) [default: NULL]

  Indexes {
    district_code [name: "indonesia_villages_district_code_foreign"]
  }
}

Table "interactive_images" {
  "id" bigint [pk, not null, increment]
  "identifier" varchar(255) [not null]
  "qrcode" varchar(255) [not null]
  "filepath" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventories" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "stock" double [not null, default: '0']
  "item_type" int [not null]
  "brand_id" int [not null]
  "supplier_id" int [default: NULL]
  "unit_id" int [default: NULL]
  "description" text
  "warranty" tinyint [default: NULL, note: 'in years']
  "year_of_purchase" year [default: NULL]
  "purchase_price" double [not null, default: '0']
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "warehouse_id" tinyint [default: NULL, note: 'Static id. 1 for office, 2 for entertaint']
}

Table "inventory_images" {
  "id" bigint [pk, not null, increment]
  "inventory_id" bigint [not null]
  "image" varchar(255) [not null]
  "is_main" tinyint(1) [not null, default: '0']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    inventory_id [name: "inventory_images_inventory_id_foreign"]
  }
}

Table "inventory_items" {
  "id" bigint [pk, not null, increment]
  "inventory_id" bigint [not null]
  "inventory_code" varchar(50) [not null]
  "status" tinyint [not null, note: '1 for in use, 2 for in repair, 3 for broke, 4 for disposal']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "current_location" tinyint [default: NULL, note: '1 for in user, 2 for in warehouse, 3 for in outside']
  "user_id" int [default: NULL]
  "qrcode" varchar(255) [default: NULL]
  "purchase_price" double [not null]
  "warranty" int [default: NULL]
  "year_of_purchase" year [default: NULL]

  Indexes {
    inventory_id [name: "inventory_items_inventory_id_foreign"]
  }
}

Table "inventory_maintenance_requests" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_position_histories" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_positions" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_request_items" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_requests" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "inventory_types" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "slug" varchar(50) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "job_batches" {
  "id" varchar(255) [pk, not null]
  "name" varchar(255) [not null]
  "total_jobs" int [not null]
  "pending_jobs" int [not null]
  "failed_jobs" int [not null]
  "failed_job_ids" longtext [not null]
  "options" mediumtext
  "cancelled_at" int [default: NULL]
  "created_at" int [not null]
  "finished_at" int [default: NULL]
}

Table "job_levels" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "uid" char(36) [not null]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "jobs" {
  "id" bigint [pk, not null, increment]
  "queue" varchar(255) [not null]
  "payload" longtext [not null]
  "attempts" tinyint [not null]
  "reserved_at" int [default: NULL]
  "available_at" int [not null]
  "created_at" int [not null]

  Indexes {
    queue [name: "jobs_queue_index"]
  }
}

Table "line_messages" {
  "id" bigint [pk, not null, increment]
  "type" varchar(255) [default: NULL]
  "user_id" varchar(255) [default: NULL]
  "message" longtext [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "menus" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "parent_id" int [default: NULL]
  "icon" varchar(255) [default: NULL]
  "link" varchar(255) [default: NULL]
  "permission" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "group" tinyint [not null]
  "lang_id" varchar(255) [default: NULL]
  "lang_en" varchar(255) [default: NULL]
  "app_type" varchar(100) [default: 'old', note: 'as a marker whether the menu is displayed in the application with the old or new design. if office then new, other than that is the old display']
  "new_icon" varchar(255) [default: NULL]
  "new_link" varchar(255) [default: NULL]
}

Table "migrations" {
  "id" int [pk, not null, increment]
  "migration" varchar(255) [not null]
  "batch" int [not null]
}

Table "model_has_permissions" {
  "permission_id" bigint [not null]
  "model_type" varchar(255) [not null]
  "model_id" bigint [not null]

  Indexes {
    (permission_id, model_id, model_type) [pk]
    (model_id, model_type) [name: "model_has_permissions_model_id_model_type_index"]
  }
}

Table "model_has_roles" {
  "role_id" bigint [not null]
  "model_type" varchar(255) [not null]
  "model_id" bigint [not null]

  Indexes {
    (role_id, model_id, model_type) [pk]
    (model_id, model_type) [name: "model_has_roles_model_id_model_type_index"]
  }
}

Table "nas_folder_creations" {
  "id" bigint [pk, not null, increment]
  "project_name" varchar(255) [not null]
  "project_id" int [not null]
  "folder_path" longtext [not null]
  "status" tinyint(1) [not null, default: '1']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "type" nas_folder_creations_type_enum [not null, default: 'create']
  "last_folder_name" longtext [not null]
  "current_folder_name" varchar(255) [default: NULL]
  "server_response" longtext
  "failed_reason" varchar(255) [default: NULL]
  "current_path" longtext
}

Table "notification_templates" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "notifications" {
  "id" char(36) [pk, not null]
  "type" varchar(255) [not null]
  "notifiable_type" varchar(255) [not null]
  "notifiable_id" bigint [not null]
  "data" text [not null]
  "read_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    (notifiable_type, notifiable_id) [name: "notifications_notifiable_type_notifiable_id_index"]
  }
}

Table "password_reset_tokens" {
  "email" varchar(255) [pk, not null]
  "token" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
}

Table "permissions" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "guard_name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "group" varchar(255) [default: NULL]

  Indexes {
    (name, guard_name) [unique, name: "permissions_name_guard_name_unique"]
  }
}

Table "personal_access_tokens" {
  "id" bigint [pk, not null, increment]
  "tokenable_type" varchar(255) [not null]
  "tokenable_id" bigint [not null]
  "name" varchar(255) [not null]
  "token" varchar(64) [not null]
  "abilities" text
  "last_used_at" timestamp [default: NULL]
  "expires_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    token [unique, name: "personal_access_tokens_token_unique"]
    (tokenable_type, tokenable_id) [name: "personal_access_tokens_tokenable_type_tokenable_id_index"]
  }
}

Table "position_backups" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "division_id" bigint [not null]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "positions" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "division_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]

  Indexes {
    division_id [name: "positions_division_id_foreign"]
  }
}

Table "price_led_guides" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "country_id" bigint [default: NULL]
  "state_id" bigint [default: NULL]
  "city_id" bigint [default: NULL]
  "price" decimal(24,2) [not null, default: '0.00']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_boards" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "name" varchar(255) [not null]
  "sort" varchar(2) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "based_board_id" int [default: NULL]

  Indexes {
    project_id [name: "project_boards_project_id_foreign"]
  }
}

Table "project_classes" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "maximal_point" tinyint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "color" varchar(20) [default: NULL]
}

Table "project_equipment" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_id" bigint [not null]
  "inventory_id" int [not null]
  "qty" int [not null]
  "status" tinyint [not null, note: '1 for ready, 2 for requested, 3 for decline']
  "project_date" date [not null]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "is_checked_pic" tinyint(1) [not null, default: '0']
  "inventory_code" varchar(30) [default: NULL]
  "is_good_condition" tinyint(1) [default: NULL]
  "detail_condition" varchar(255) [default: NULL]
  "is_returned" tinyint(1) [default: NULL]

  Indexes {
    project_id [name: "project_equipment_project_id_foreign"]
  }
}

Table "project_led_settings" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_logs" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "message" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "project_logs_project_id_foreign"]
  }
}

Table "project_marketings" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "marketing_id" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "project_marketings_project_id_foreign"]
  }
}

Table "project_person_in_charges" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "pic_id" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "project_person_in_charges_project_id_foreign"]
  }
}

Table "project_references" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "media_path" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "name" varchar(255) [default: NULL]
  "type" varchar(100) [default: NULL]
  "folder" varchar(150) [default: NULL]

  Indexes {
    project_id [name: "project_references_project_id_foreign"]
  }
}

Table "project_song_lists" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_id" bigint [not null]
  "name" varchar(255) [not null]
  "is_request_edit" tinyint(1) [not null, default: '0']
  "is_request_delete" tinyint(1) [not null, default: '0']
  "created_by" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "target_name" varchar(255) [default: NULL]
  "reason" varchar(255) [default: NULL]

  Indexes {
    project_id [name: "project_song_lists_project_id_foreign"]
  }
}

Table "project_task_attachments" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "project_id" bigint [not null]
  "media" varchar(255) [default: NULL]
  "display_name" varchar(255) [default: NULL]
  "related_task_id" int [default: NULL]
  "type" tinyint [not null, note: '1 for media, 2 for other task link, 3 for external link']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_attachments_project_task_id_foreign"]
    project_id [name: "project_task_attachments_project_id_foreign"]
  }
}

Table "project_task_holds" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_task_id" bigint [not null]
  "reason" varchar(255) [not null]
  "hold_at" timestamp [default: NULL]
  "end_at" timestamp [default: NULL]
  "hold_by" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_holds_project_task_id_foreign"]
  }
}

Table "project_task_logs" {
  "id" bigint [pk, not null, increment]
  "project_task_id" int [default: NULL]
  "type" varchar(255) [default: NULL]
  "text" varchar(255) [default: NULL]
  "user_id" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_task_pic_histories" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "project_task_id" bigint [not null]
  "employee_id" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_id [name: "project_task_pic_histories_project_id_foreign"]
    project_task_id [name: "project_task_pic_histories_project_task_id_foreign"]
  }
}

Table "project_task_pic_logs" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "employee_id" int [not null]
  "work_type" varchar(30) [not null, note: 'will be: assigned, on_progress, check_by_pm, revise, finish']
  "time_added" timestamp [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_pic_logs_project_task_id_foreign"]
  }
}

Table "project_task_pics" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "status" varchar(1) [default: NULL]
  "assigned_at" timestamp [default: NULL]
  "approved_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_pics_project_task_id_foreign"]
    employee_id [name: "project_task_pics_employee_id_foreign"]
  }
}

Table "project_task_pic_deadlines" {
  "id" bigint [pk, not null, increment]
  "employee_id" bigint [ref: > employees.id]
  "project_task_id" bigint [ref: >  project_tasks.id]
  "project_id" bgint [ref: > projects.id]
  "start_time" timestamp
  "end_time" timestamp
  "complete_time" timestamp
  "working_time" varchar [note: "Total of working time"]
  "project_board_id" bigint [ref: > project_boards.id]
  "type" project_task_deadline_type
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_task_proof_of_works" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "project_id" int [not null]
  "nas_link" varchar(255) [default: NULL]
  "preview_image" longtext
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_year" year [default: NULL]
  "created_month" tinyint [default: NULL]

  Indexes {
    project_task_id [name: "project_task_proof_of_works_project_task_id_foreign"]
  }
}

Table "project_task_revise_histories" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "project_id" int [default: NULL]
  "selected_user" longtext [note: 'who is working on this revise task']
  "reason" varchar(255) [default: NULL]
  "file" varchar(255) [default: NULL]
  "revise_by" int [default: NULL, note: 'who is create this revise reason (base on employee id)']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_revise_histories_project_task_id_foreign"]
  }
}

Table "project_task_worktimes" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [not null]
  "employee_id" int [default: NULL]
  "user_id" int [default: NULL]
  "project_id" int [default: NULL]
  "start_at" timestamp [default: NULL]
  "end_at" timestamp [default: NULL]
  "work_type" project_task_worktimes_work_type_enum [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    project_task_id [name: "project_task_worktimes_project_task_id_foreign"]
  }
}

Table "project_tasks" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_id" bigint [not null]
  "project_board_id" bigint [not null]
  "start_date" date [default: NULL]
  "end_date" date [default: NULL]
  "description" text
  "name" varchar(255) [not null]
  "start_working_at" datetime [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "task_type" project_tasks_task_type_enum [default: NULL]
  "performance_time" longtext [note: '''will be [{type: \'\'on_progress\'\', start_at: \'\'2024-05-24 20:00:00\'\', end_at: \'\'\'\'}]. and will be have type: on_progress, review_by_pm, review_by_client''']
  "status" tinyint [default: NULL, note: '1 for on process, 2 for check by pm, 3 for revise, 4 for completed']
  "current_pics" longtext [note: 'This column will be update in every task movement. Format will be array of id like [1,2,3]']
  "current_board" int [default: NULL]p
  "is_approved" tinyint [not null, default: '0']
  "task_identifier_id" varchar(4) [default: NULL]
  "is_modeler_task" tinyint(1) [not null, default: '0', note: 'This column is to detect this task is assign to modeler team or not']

  Indexes {
    task_identifier_id [unique, name: "project_tasks_task_identifier_id_unique"]
    project_id [name: "project_tasks_project_id_foreign"]
    project_board_id [name: "project_tasks_project_board_id_foreign"]
  }
}

Table "deadline_change_reasons" {
  "id" bigint [pk, not null, increment]
  "name" varchar [not null]
  "created_at" timestamp
  "updated_at" timestamp
  "deleted_at" timestamp
}

Table "project_task_deadlines" {
  "id" bigint [pk, not null, increment]
  "project_task_id" bigint [ref: > project_tasks.id]
  "employee_id" bigint [ref: > employees.id]
  "deadline" timestamp [not null]
  "actual_finish_time" timestamp
  "is_first_deadline" bool [not null, default: false]
  "due_reason" bigint [ref: > deadline_change_reasons, note: "nullable"]
  "custom_reason" varchar
  "updated_by" bigint [ref: > users.id]
  "created_at" timestamp
  "updated_at" timestamp
}

Table "project_vjs" {
  "id" bigint [pk, not null, increment]
  "project_id" bigint [not null]
  "employee_id" bigint [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "created_by" int [not null]

  Indexes {
    project_id [name: "project_vjs_project_id_foreign"]
    employee_id [name: "project_vjs_employee_id_foreign"]
  }
}

Table "projects" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "client_portal" varchar(255) [not null]
  "project_date" date [not null]
  "event_type" projects_event_type_enum [default: NULL]
  "venue" varchar(255) [not null]
  "marketing_id" int [default: NULL]
  "collaboration" varchar(255) [default: NULL]
  "note" text
  "status" tinyint [default: NULL]
  "created_by" int [default: NULL]
  "updated_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "led_area" double [not null, default: '0']
  "led_detail" longtext
  "uid" char(36) [not null]
  "showreels" varchar(255) [default: NULL]
  "country_id" int [default: NULL]
  "state_id" int [default: NULL]
  "city_id" int [default: NULL]
  "city_name" varchar(255) [default: NULL]
  "project_class_id" int [default: NULL]
  "classification" varchar(255) [default: NULL]
  "showreels_status" tinyint [default: NULL]
  "longitude" varchar(150) [default: NULL]
  "latitude" varchar(150) [default: NULL]
  "feedback" text

  "project_deal_id" bigint [ref: > project_deals.id]
}

Table "project_task_duration_histories" {
    "id" bigint [pk, increment, not null]
    "created_at" timestamp [not null]
    "project_id" bigint [not null, note: 'References the related project', ref: > projects.id]
    "task_id" bigint [not null, note: 'References the related project task', ref: > project_tasks.id]
    "pic_id" bigint [not null, note: 'References the person in charge (PIC) who worked on the task', ref: > employees.id]
    "task_duration" bigint [not null, note: 'Duration spent on the task (duration in second)']
    "pm_approval_duration" bigint [not null, note: 'Duration spent on PM clicked finish']
    "task_type" project_task_duration_history_enums [values: cross_team_collaboration, single_assignee, temporary_transfer, split_assignment, note: 'Type of task assignment']
    "is_task_revised" boolean [default: false, note: 'Indicates if the task was revised']
    "is_task_deadline_updated" boolean [default: false, note: 'Indicates if the task deadline was updated']
    Note: 'Stores duration logs for tasks, with type and revision status'

    Indexes {
      (project_id) [name: 'project_task_duration_histories_project_id_idx']
      (task_id) [name: 'project_task_duration_histories_task_id_idx']
      (pic_id) [name: 'project_task_duration_histories_pic_id_idx']
    }
}

Table "project_metas" {
  "id" bigint [not null, pk, increment]
  "project_id" bigint [ref: > projects.id]
  "teams_meta" longtext [note: 'Structure will be like: [{"pic_id": number, "teams": [number,number], "team_transfer": [number,number]}]']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "quotation_items" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_deals" {
  "id" bigint [pk, increment, not null]
  "name" varchar(255) [not null]
  "project_date" date [not null]
  "customer_id" bigint [ref: > customers.id]
  "event_type" projects_event_type_enum [default: NULL]
  "venue" varchar(255) [not null]
  "marketing_id" int [default: NULL]
  "collaboration" varchar(255) [default: NULL]
  "note" text
  "led_area" double [not null, default: '0']
  "led_detail" json [default: NULL, note: '[{"name":"main","led":[{"width":"1","height":"1"}],"total":"1 m<sup>2<\/sup>","totalRaw":"1","textDetail":"1 x 1 m"}]']
  "country_id" int [default: NULL]
  "state_id" int [default: NULL]
  "city_id" int [default: NULL]
  "city_name" varchar(255) [default: NULL]
  "project_class_id" int [default: NULL]
  "longitude" varchar(150) [default: NULL]
  "latitude" varchar(150) [default: NULL]
  "equipment_type" project_deal_equipment_type
  "identifier_number" varchar(100) [note: "This number will be used on all quotation and all transactions"]
  "is_high_season" bool
  "is_fully_paid" boolean [default: false, note: "Define this project has been paid off or not"]
  "cancel_reason" varchar(255)
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "deleted_at" timestamp [default: NULL]

  Indexes {
    identifier_number [unique, name: "project_deals_identifier_number_unique"]
  }
}

Table "project_deal_changes" {
  "id" bigint [pk, increment not null]
  "project_deal_id" bigint [ref: > project_deals.id]
  "detail_changes" longtext [note: 'Will be JSON format. Json will be like this [{"field": "project_date", "old_value": "", "new_value": "", "label": ""}]']
  "requested_by" bigint [ref: > users.id]
  "requested_at" timestamp
  "approval_by" bigint [ref: > users.id]
  "approval_at" timestamp
  "rejected_at" timestamp
  "rejected_by" bigint [ref: > users.id]
  "status" project_deal_changes_status
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_quotations" {
  "id" bigint [pk, not null, increment]
  "project_deal_id" bigint [ref: > project_deals.id]
  "main_ballroom" decimal [default: 0]
  "prefunction" decimal [default: 0]
  "high_season_fee" decimal [default: 0]
  "equipment_fee" decimal [default: 0]
  "sub_total" decimal [default: 0]
  "maximum_discount" decimal [default: 0]
  "total" decimal [default: 0]
  "maximum_markup_price" decimal [default: 0]
  "fix_price" decimal [default: 0]
  "quotation_id" varchar
  "is_final" bool [default: "false"]
  "description" text
  "design_job" varchar(100) [default: null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "project_quotation_items" {
  "id" bigint [pk, not null, increment]
  "quotation_id" bigint [ref: > project_quotations.id]
  "item_id" bigint [ref: > quotation_items.id]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "export_import_results" {
  "id" bigint [pk, not null, increment]
  "area" varchar(100) [not null]
  "description" varchar(255) [not null]
  "message" longtext [not null]
  "user_id" bigint [ref: > users.id]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "invoices" {
  note: "This invoices table used to record all request invoice from marketing team to customer"

  "id" bigint [pk, not null, increment]
  "amount" decimal [default: 0]
  "paid_amount" decimal [default: 0]
  "payment_date" timestamp
  "payment_due" timestamp
  "project_deal_id" bigint [ref: > project_deals.id]
  "customer_id" bigint [ref: > customers.id]
  "status" invoice_statuses
  "is_down_payment" boolean [default: false, note: "Define this invoice is down payment or not"]
  "raw_data" longtext

  // numbering
  "parent_number" varchar(100) [not null]
  "number" varchar (100) [not null]
  "is_main" boolean [default: false]
  "sequence" tinyint [note: "Sequence identifier for child invoice"]

  "created_by" bigint [ref: > users.id]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "invoice_request_updates" {
  "id" bigint [pk, not null, increment]
  "invoice_id" bigint [ref: > invoices.id]
  "amount" decimal [default: 0]
  "payment_date" date
  "status" tinyint [note: "1 for approved, 2 for pending", default: 2]
  "request_by" bigint [ref: > users.id]
  "approved_by" bigint [ref: > users.id]
  "rejected_by" bigint [ref: > users.id]
  "reason" text [default: NULL]
  "approved_at" timestamp [default: NULL]
  "rejected_at" timestamp [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "transactions" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_deal_id" bigint [ref: > project_deals.id]
  "customer_id" bigint [ref: > customers.id]
  "payment_amount" decimal [default: 0]
  "reference" varchar
  "note" varchar(255)
  "trx_id" varchar(255) [not null]
  "inovice_id" bigint [ref: > invoices.id]
  "transaction_date" timestamp [default: NULL]
  "transaction_type" transaction_enum
  "created_by" bigint [ref: > users.id]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "transaction_images" {
  "id" bigint [pk, not null, increment]
  "transaction_id" bigint [ref: > transactions.id]
  "image" varchar [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "request_inventories" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "description" text
  "price" double [not null, default: '0']
  "quantity" tinyint [not null, default: '0']
  "purchase_source" varchar(255) [default: NULL]
  "purchase_link" longtext
  "status" tinyint [not null, default: '1', note: '1 for requested, 2 for approved, 3 for rejected']
  "requested_by" int [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "approval_target" longtext
  "store_name" varchar(255) [default: NULL]
  "approved_by" int [default: NULL]
  "rejected_by" int [default: NULL]
}

Table "role_has_permissions" {
  "permission_id" bigint [not null]
  "role_id" bigint [not null]

  Indexes {
    (permission_id, role_id) [pk]
    role_id [name: "role_has_permissions_role_id_foreign"]
  }
}

Table "roles" {
  "id" bigint [pk, not null, increment]
  "name" varchar(255) [not null]
  "guard_name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "is_permanent" tinyint(1) [not null, default: '0']

  Indexes {
    (name, guard_name) [unique, name: "roles_name_guard_name_unique"]
  }
}

Table "sessions" {
  "id" varchar(255) [pk, not null]
  "user_id" bigint [default: NULL]
  "ip_address" varchar(45) [default: NULL]
  "user_agent" text
  "payload" longtext [not null]
  "last_activity" int [not null]

  Indexes {
    user_id [name: "sessions_user_id_index"]
    last_activity [name: "sessions_last_activity_index"]
  }
}

Table "settings" {
  "id" bigint [pk, not null, increment]
  "key" varchar(255) [default: NULL]
  "value" longtext
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "code" varchar(255) [default: NULL]
}

Table "states" {
  "id" bigint [pk, not null, increment]
  "country_id" bigint [not null]
  "name" varchar(255) [not null]
  "country_code" varchar(255) [not null]
}

Table "suppliers" {
  "id" bigint [pk, not null, increment]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
}

Table "telegram_chat_commands" {
  "id" bigint [pk, not null, increment]
  "chat_id" varchar(255) [not null]
  "command" varchar(255) [not null]
  "status" tinyint(1) [not null, default: '1']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "current_function" varchar(255) [default: NULL]
}

Table "telegram_chat_histories" {
  "id" bigint [pk, not null, increment]
  "chat_id" varchar(255) [not null]
  "message" text [not null]
  "message_id" varchar(255) [default: NULL]
  "status" tinyint [not null, default: '1', note: '1 for processing, 2 for success, 3 for failed']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "chat_type" varchar(255) [default: NULL]
  "bot_command" varchar(255) [default: NULL]
  "from_customer" tinyint(1) [not null, default: '0']
  "is_closed" tinyint(1) [not null, default: '0']
  "topic" varchar(255) [default: NULL]
}

Table "telegram_report_tasks" {
  "id" bigint [pk, not null, increment]
  "task_id" int [default: NULL]
  "telegram_chat_id" varchar(255) [default: NULL]
  "nas_link" varchar(255) [default: NULL]
  "file_id" varchar(255) [default: NULL]
  "mime_type" varchar(255) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "telegram_sessions" {
  "id" bigint [pk, not null, increment]
  "chat_id" varchar(255) [not null]
  "value" varchar(255) [not null]
  "status" tinyint(1) [not null, default: '1']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "telegram_transactions" {
  "id" bigint [pk, not null, increment]
  "chat_id" varchar(255) [not null]
  "message_id" varchar(255) [not null]
  "identity" varchar(255) [not null]
  "status" tinyint(1) [not null, default: '1']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "telescope_entries" {
  "sequence" bigint [pk, not null, increment]
  "uuid" char(36) [not null]
  "batch_id" char(36) [not null]
  "family_hash" varchar(255) [default: NULL]
  "should_display_on_index" tinyint(1) [not null, default: '1']
  "type" varchar(20) [not null]
  "content" longtext [not null]
  "created_at" datetime [default: NULL]

  Indexes {
    uuid [unique, name: "telescope_entries_uuid_unique"]
    batch_id [name: "telescope_entries_batch_id_index"]
    family_hash [name: "telescope_entries_family_hash_index"]
    created_at [name: "telescope_entries_created_at_index"]
    (type, should_display_on_index) [name: "telescope_entries_type_should_display_on_index_index"]
  }
}

Table "telescope_entries_tags" {
  "entry_uuid" char(36) [not null]
  "tag" varchar(255) [not null]

  Indexes {
    (entry_uuid, tag) [pk]
    tag [name: "telescope_entries_tags_tag_index"]
  }
}

Table "telescope_monitoring" {
  "tag" varchar(255) [pk, not null]
}

Table "transfer_team_members" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "project_id" bigint [not null]
  "employee_id" int [default: NULL]
  "request_to" int [not null]
  "reason" varchar(255) [not null]
  "project_date" date [not null]
  "request_at" timestamp [default: NULL]
  "approved_at" timestamp [default: NULL]
  "completed_at" timestamp [default: NULL]
  "rejected_at" timestamp [default: NULL]
  "canceled_at" timestamp [default: NULL]
  "reject_reason" varchar(255) [default: NULL]
  "device_action" varchar(10) [default: NULL, note: 'device resource for any action take. It should line or web']
  "status" tinyint [not null, note: '1 for requested, 2 for approved, 3 for reject, 4 completed']
  "requested_by" int [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "alternative_employee_id" int [default: NULL]
  "is_entertainment" tinyint(1) [not null, default: '0']

  Indexes {
    project_id [name: "transfer_team_members_project_id_foreign"]
  }
}

Table "units" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "name" varchar(255) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "user_encrypted_tokens" {
  "id" bigint [pk, not null, increment]
  "user_id" int [not null]
  "data" longtext [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Table "user_inventories" {
  "id" bigint [pk, not null, increment]
  "inventory_id" bigint [not null]
  "quantity" tinyint [not null, default: '1']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "user_inventory_master_id" bigint [not null]
  "inventory_type" varchar(20) [not null]
  "custom_inventory_id" int [default: NULL]

  Indexes {
    inventory_id [name: "user_inventories_inventory_id_foreign"]
    user_inventory_master_id [name: "user_inventories_user_inventory_master_id_foreign"]
  }
}

Table "user_inventory_masters" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "employee_id" bigint [not null]
  "total_inventory" int [not null, default: '0']
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]

  Indexes {
    employee_id [name: "user_inventory_masters_employee_id_foreign"]
  }
}

Table "user_login_histories" {
  "id" bigint [pk, not null, increment]
  "user_id" int [not null]
  "login_at" timestamp [not null]
  "ip" varchar(100) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "browser" varchar(200) [default: NULL]
}

Table "users" {
  "id" bigint [pk, not null, increment]
  "uid" char(36) [not null]
  "email" varchar(255) [not null]
  "email_verified_at" timestamp [default: NULL]
  "password" varchar(255) [not null]
  "image" varchar(255) [default: NULL]
  "last_login_at" timestamp [default: NULL]
  "remember_token" varchar(100) [default: NULL]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
  "is_external_user" tinyint(1) [not null, default: '0']
  "username" varchar(255) [default: NULL]
  "employee_id" int [default: NULL]
  "is_employee" tinyint(1) [default: NULL]
  "is_project_manager" tinyint(1) [default: NULL]
  "is_director" tinyint(1) [default: NULL]
  "reset_password_token_exp" timestamp [default: NULL]
  "reset_password_token_claim" tinyint(1) [default: NULL]
  "deleted_at" timestamp [default: NULL]

  Indexes {
    email [unique, name: "users_email_unique"]
  }
}

Table "client_portals" {
  "id" bigint [pk, increment, not null]
  "original_link" varchar(255) [not null]
  "link" varchar(100) [not null]
  "created_at" timestamp [default: NULL]
  "updated_at" timestamp [default: NULL]
}

Ref "custom_inventory_details_custom_inventory_id_foreign":"custom_inventories"."id" < "custom_inventory_details"."custom_inventory_id" [delete: cascade]

Ref "employee_custom_inventories_custom_inventory_id_foreign":"custom_inventories"."id" < "employee_custom_inventories"."custom_inventory_id" [delete: cascade]

Ref "employee_custom_inventories_employee_id_foreign":"employees"."id" < "employee_custom_inventories"."employee_id" [delete: cascade]

Ref "employee_emergency_contacts_employee_id_foreign":"employees"."id" < "employee_emergency_contacts"."employee_id" [delete: cascade]

Ref "employee_families_employee_id_foreign":"employees"."id" < "employee_families"."employee_id" [delete: cascade]

Ref "employee_inventory_items_employee_inventory_master_id_foreign":"employee_inventory_masters"."id" < "employee_inventory_items"."employee_inventory_master_id" [delete: cascade]

Ref "employee_inventory_items_inventory_item_id_foreign":"inventory_items"."id" < "employee_inventory_items"."inventory_item_id" [delete: cascade]

Ref "employee_inventory_masters_employee_id_foreign":"employees"."id" < "employee_inventory_masters"."employee_id" [delete: cascade]

Ref "employee_point_details_employee_point_id_foreign":"employee_points"."id" < "employee_point_details"."employee_point_id" [delete: cascade]

Ref "employee_point_project_details_point_id_foreign":"employee_point_projects"."id" < "employee_point_project_details"."point_id" [delete: cascade]

Ref "employee_point_projects_employee_point_id_foreign":"employee_points"."id" < "employee_point_projects"."employee_point_id" [delete: cascade]

Ref "employee_points_employee_id_foreign":"employees"."id" < "employee_points"."employee_id"

Ref "employee_resigns_employee_id_foreign":"employees"."id" < "employee_resigns"."employee_id" [delete: set null]

Ref "employees_position_id_foreign":"position_backups"."id" < "employees"."position_id"

Ref "entertainment_task_song_logs_project_song_list_id_foreign":"project_song_lists"."id" < "entertainment_task_song_logs"."project_song_list_id" [delete: cascade]

Ref "entertainment_task_song_result_images_result_id_foreign":"entertainment_task_song_results"."id" < "entertainment_task_song_result_images"."result_id" [delete: cascade]

Ref "entertainment_task_song_results_task_id_foreign":"entertainment_task_songs"."id" < "entertainment_task_song_results"."task_id" [delete: cascade]

Ref "entertainment_task_songs_employee_id_foreign":"employees"."id" < "entertainment_task_songs"."employee_id"

Ref "entertainment_task_songs_project_id_foreign":"projects"."id" < "entertainment_task_songs"."project_id"

Ref "entertainment_task_songs_project_song_list_id_foreign":"project_song_lists"."id" < "entertainment_task_songs"."project_song_list_id" [delete: cascade]

Ref "event_equipment_details_custom_detail_id_foreign":"custom_inventory_details"."id" < "event_equipment_details"."custom_detail_id"

Ref "event_equipment_details_event_equipment_id_foreign":"event_equipments"."id" < "event_equipment_details"."event_equipment_id" [delete: cascade]

Ref "event_equipment_details_inventory_item_id_foreign":"inventory_items"."id" < "event_equipment_details"."inventory_item_id"

Ref "event_equipments_project_id_foreign":"projects"."id" < "event_equipments"."project_id" [delete: cascade]

Ref "event_equipments_requested_by_foreign":"employees"."id" < "event_equipments"."requested_by"

Ref "indonesia_districts_city_code_foreign":"indonesia_cities"."code" < "indonesia_districts"."city_code" [update: cascade]

Ref "indonesia_villages_district_code_foreign":"indonesia_districts"."code" < "indonesia_villages"."district_code" [update: cascade]

Ref "inventory_images_inventory_id_foreign":"inventories"."id" < "inventory_images"."inventory_id" [delete: cascade]

Ref "inventory_items_inventory_id_foreign":"inventories"."id" < "inventory_items"."inventory_id" [delete: cascade]

Ref "model_has_permissions_permission_id_foreign":"permissions"."id" < "model_has_permissions"."permission_id" [delete: cascade]

Ref "model_has_roles_role_id_foreign":"roles"."id" < "model_has_roles"."role_id" [delete: cascade]

Ref "positions_division_id_foreign":"divisions"."id" < "positions"."division_id" [delete: cascade]

Ref "project_boards_project_id_foreign":"projects"."id" < "project_boards"."project_id" [delete: cascade]

Ref "project_equipment_project_id_foreign":"projects"."id" < "project_equipment"."project_id" [delete: cascade]

Ref "project_logs_project_id_foreign":"projects"."id" < "project_logs"."project_id" [delete: cascade]

Ref "project_marketings_project_id_foreign":"projects"."id" < "project_marketings"."project_id" [delete: cascade]

Ref "project_person_in_charges_project_id_foreign":"projects"."id" < "project_person_in_charges"."project_id"

Ref "project_references_project_id_foreign":"projects"."id" < "project_references"."project_id" [delete: cascade]

Ref "project_song_lists_project_id_foreign":"projects"."id" < "project_song_lists"."project_id"

Ref "project_task_attachments_project_id_foreign":"projects"."id" < "project_task_attachments"."project_id" [delete: cascade]

Ref "project_task_attachments_project_task_id_foreign":"project_tasks"."id" < "project_task_attachments"."project_task_id" [delete: cascade]

Ref "project_task_holds_project_task_id_foreign":"project_tasks"."id" < "project_task_holds"."project_task_id" [delete: cascade]

Ref "project_task_pic_histories_project_id_foreign":"projects"."id" < "project_task_pic_histories"."project_id" [delete: cascade]

Ref "project_task_pic_histories_project_task_id_foreign":"project_tasks"."id" < "project_task_pic_histories"."project_task_id" [delete: cascade]

Ref "project_task_pic_logs_project_task_id_foreign":"project_tasks"."id" < "project_task_pic_logs"."project_task_id" [delete: cascade]

Ref "project_task_pics_employee_id_foreign":"employees"."id" < "project_task_pics"."employee_id" [delete: cascade]

Ref "project_task_pics_project_task_id_foreign":"project_tasks"."id" < "project_task_pics"."project_task_id" [delete: cascade]

Ref "project_task_proof_of_works_project_task_id_foreign":"project_tasks"."id" < "project_task_proof_of_works"."project_task_id" [delete: cascade]

Ref "project_task_revise_histories_project_task_id_foreign":"project_tasks"."id" < "project_task_revise_histories"."project_task_id" [delete: cascade]

Ref "project_task_worktimes_project_task_id_foreign":"project_tasks"."id" < "project_task_worktimes"."project_task_id" [delete: cascade]

Ref "project_tasks_project_board_id_foreign":"project_boards"."id" < "project_tasks"."project_board_id" [delete: cascade]

Ref "project_tasks_project_id_foreign":"projects"."id" < "project_tasks"."project_id" [delete: cascade]

Ref "project_vjs_employee_id_foreign":"employees"."id" < "project_vjs"."employee_id" [delete: cascade]

Ref "project_vjs_project_id_foreign":"projects"."id" < "project_vjs"."project_id" [delete: cascade]

Ref "role_has_permissions_permission_id_foreign":"permissions"."id" < "role_has_permissions"."permission_id" [delete: cascade]

Ref "role_has_permissions_role_id_foreign":"roles"."id" < "role_has_permissions"."role_id" [delete: cascade]

Ref "telescope_entries_tags_entry_uuid_foreign":"telescope_entries"."uuid" < "telescope_entries_tags"."entry_uuid" [delete: cascade]

Ref "transfer_team_members_project_id_foreign":"projects"."id" < "transfer_team_members"."project_id" [delete: cascade]

Ref "user_inventories_inventory_id_foreign":"inventory_items"."id" < "user_inventories"."inventory_id" [delete: cascade]

Ref "user_inventories_user_inventory_master_id_foreign":"user_inventory_masters"."id" < "user_inventories"."user_inventory_master_id" [delete: cascade]

Ref "user_inventory_masters_employee_id_foreign":"employees"."id" < "user_inventory_masters"."employee_id" [delete: cascade]

