<?php

namespace Modules\Production\Repository;

use App\Repository\BaseRepository;
use Modules\Production\Models\ProjectSong;
use Modules\Production\Models\ProjectSongItem;
use Ramsey\Uuid\Uuid;

class ProjectSongRepository extends BaseRepository
{
    public function __construct(ProjectSong $model)
    {
        return parent::__construct($model);
    }

    /**
     * Store detail of songs in each group.
     *
     * Upserted in bulk, which bypasses model events - so the uid normally
     * generated by the ModelObserver trait is built here instead.
     *
     * @param  array<int,string>  $songs
     */
    public function storeSongs(int $groupId, array $songs): bool
    {
        $payload = collect($songs)->map(function (string $song) use ($groupId) {
            return [
                'project_song_id' => $groupId,
                'song_name' => $song,
                'uid' => Uuid::uuid4()->toString(),
            ];
        })->toArray();

        return (bool) ProjectSongItem::upsert(
            $payload,
            ['project_song_id', 'song_name'],
            ['song_name']
        );
    }
}
