name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
        with:
          fetch-depth: 0  # Get complete history to ensure proper checkout

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Match your VPS PHP version
          extensions: mbstring, xml, ctype, json, tokenizer, openssl, pdo, pdo_mysql, gd  # Common Laravel extensions
          tools: composer:v2.8.10  # Match your VPS Composer version

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -a
            sudo su - deployer
            /var/www/apps/scripts/backend.sh
