name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
        with:
          fetch-depth: 0  # Get complete history to ensure proper checkout

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Match your VPS PHP version
          extensions: mbstring, xml, ctype, json, tokenizer, openssl, pdo, pdo_mysql, gd  # Common Laravel extensions
          tools: composer:v2.8.10  # Match your VPS Composer version

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/apps/backend.dfactory.pro
            
            # Fix permissions and ownership
            sudo chown -R www-data:www-data .
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type f -exec chmod 644 {} \;
            sudo chmod -R 777 storage bootstrap/cache
            
            # Cleanup and prepare
            rm -rf bootstrap/cache/*.php
            rm -rf storage/framework/cache/*
            
            # Git operations
            git config --global --add safe.directory /var/www/apps/backend.dfactory.pro
            git pull origin staging
            
            # Composer operations
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            composer dump-autoload -o
            
            # Laravel specific
            php artisan storage:link
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
