<?php

use App\Data\Finance\CostCenter\ListCostCenterData;
use App\Data\Finance\CostCenter\StoreCostCenterData;
use App\Data\Finance\CostCenter\UpdateCostCenterData;
use App\Enums\Finance\CostCenter\CostCenterType;
use App\Models\User;
use Modules\Finance\Models\CostCenter;
use Modules\Finance\Services\CostCenterService;

use function Pest\Laravel\actingAs;
use function Pest\Laravel\assertDatabaseHas;
use function Pest\Laravel\assertDatabaseMissing;

/**
 * CostCenterService and the CostCenterController endpoints under /api/accounting/cost-centers.
 *
 * The service is a thin CRUD over CostCenter: list (paginated + filtered), store, update and
 * delete. Parents are limited to a single level (getParent() rejects a parent that already has a
 * parent), and a missing uid raises DataNotFound. uid is auto-generated by the ModelObserver.
 */
function ccService(): CostCenterService
{
    return app(CostCenterService::class);
}

/**
 * Create + authenticate a user (the accounting routes are behind auth.session).
 */
function ccActor(): User
{
    $user = User::factory()->create();
    actingAs($user);

    return $user;
}

/**
 * Persist a cost center directly (uid is set by the ModelObserver on create).
 */
function ccMake(array $attrs = []): CostCenter
{
    return CostCenter::create(array_merge([
        'code' => 'CC-'.uniqid(),
        'name' => 'Center '.uniqid(),
        'type' => CostCenterType::Department->value,
        'is_active' => true,
        'parent_id' => null,
    ], $attrs));
}

describe('list', function () {
    it('returns the paginated cost centers with a total count (service)', function () {
        request()->merge(['limit' => 10]);
        ccMake(['code' => 'CC-1', 'name' => 'HR']);
        ccMake(['code' => 'CC-2', 'name' => 'Finance']);

        $response = ccService()->list();

        expect($response['error'])->toBeFalse()
            ->and($response['message'])->toBe(__('global.success'))
            ->and($response['data']['totalData'])->toBe(2)
            ->and($response['data']['paginated'])->toHaveCount(2)
            ->and($response['data']['paginated'][0])->toBeInstanceOf(ListCostCenterData::class);
    });

    it('filters the page by a name search while the total stays unfiltered (service)', function () {
        request()->merge(['limit' => 10, 'search' => 'Finance']);
        ccMake(['code' => 'CC-1', 'name' => 'HR']);
        ccMake(['code' => 'CC-2', 'name' => 'Finance Dept']);

        $response = ccService()->list();

        expect($response['data']['paginated'])->toHaveCount(1)
            ->and($response['data']['paginated'][0]->name)->toBe('Finance Dept')
            ->and($response['data']['totalData'])->toBe(2); // totalData counts every cost center
    });

    it('exposes the parent uid and name on a child row (service)', function () {
        request()->merge(['limit' => 10]);
        $parent = ccMake(['code' => 'CC-P', 'name' => 'Parent']);
        ccMake(['code' => 'CC-C', 'name' => 'Child', 'parent_id' => $parent->id]);

        $response = ccService()->list();

        $child = collect($response['data']['paginated'])->firstWhere('code', 'CC-C');
        expect($child->parentUid)->toBe($parent->uid)
            ->and($child->parentName)->toBe('Parent');
    });

    it('lists via the endpoint (e2e)', function () {
        ccActor();
        ccMake(['code' => 'CC-1', 'name' => 'HR']);

        $this->getJson('/api/accounting/cost-centers?limit=10')
            ->assertStatus(201)
            ->assertJsonPath('data.totalData', 1)
            ->assertJsonPath('data.paginated.0.code', 'CC-1');
    });
});

describe('store', function () {
    it('creates a top level cost center (service)', function () {
        $payload = StoreCostCenterData::from([
            'code' => 'CC-100',
            'name' => 'Marketing',
            'type' => 'division',
            'parent_uid' => null,
        ]);

        $response = ccService()->store($payload);

        expect($response['error'])->toBeFalse()
            ->and($response['message'])->toBe(__('global.costCenterCreated'));
        assertDatabaseHas('cost_centers', [
            'code' => 'CC-100',
            'name' => 'Marketing',
            'type' => 'division',
            'parent_id' => null,
        ]);
    });

    it('creates a cost center under a top level parent (service)', function () {
        $parent = ccMake(['code' => 'CC-P', 'name' => 'Parent']);

        $response = ccService()->store(StoreCostCenterData::from([
            'code' => 'CC-C',
            'name' => 'Child',
            'type' => 'department',
            'parent_uid' => $parent->uid,
        ]));

        expect($response['error'])->toBeFalse();
        assertDatabaseHas('cost_centers', ['code' => 'CC-C', 'parent_id' => $parent->id]);
    });

    it('rejects a parent that already has a parent (service)', function () {
        $grandparent = ccMake(['code' => 'CC-GP', 'name' => 'GP']);
        $parent = ccMake(['code' => 'CC-P', 'name' => 'P', 'parent_id' => $grandparent->id]);

        $response = ccService()->store(StoreCostCenterData::from([
            'code' => 'CC-C',
            'name' => 'C',
            'type' => 'department',
            'parent_uid' => $parent->uid,
        ]));

        expect($response['error'])->toBeTrue();
        assertDatabaseMissing('cost_centers', ['code' => 'CC-C']);
    });

    it('creates via the endpoint (e2e)', function () {
        ccActor();

        $this->postJson('/api/accounting/cost-centers', [
            'code' => 'CC-200',
            'name' => 'Operations',
            'type' => 'department',
            'parent_uid' => null,
        ])->assertStatus(201);

        assertDatabaseHas('cost_centers', ['code' => 'CC-200', 'name' => 'Operations']);
    });

    it('rejects a duplicate code via the endpoint (e2e)', function () {
        ccActor();
        ccMake(['code' => 'CC-DUP', 'name' => 'Existing']);

        $this->postJson('/api/accounting/cost-centers', [
            'code' => 'CC-DUP',
            'name' => 'New One',
            'type' => 'department',
            'parent_uid' => null,
        ])->assertStatus(422);
    });
});

describe('update', function () {
    it('updates the editable fields but preserves is_active (service)', function () {
        $cc = ccMake(['code' => 'CC-U', 'name' => 'Old', 'is_active' => true]);

        $response = ccService()->update(UpdateCostCenterData::from([
            'code' => 'CC-U',
            'name' => 'New Name',
            'type' => 'branch',
            'parent_uid' => null,
            'is_active' => false, // ignored by update(); the active flag is changed via toggleStatus()
        ]), $cc->uid);

        expect($response['error'])->toBeFalse()
            ->and($response['message'])->toBe(__('global.costCenterUpdated'));
        assertDatabaseHas('cost_centers', [
            'id' => $cc->id,
            'name' => 'New Name',
            'type' => 'branch',
            'is_active' => true, // preserved: update() no longer edits the active flag
        ]);
    });

    it('detaches the parent when parent_uid is null (service)', function () {
        $parent = ccMake(['code' => 'CC-P', 'name' => 'P']);
        $cc = ccMake(['code' => 'CC-C', 'name' => 'C', 'parent_id' => $parent->id]);

        ccService()->update(UpdateCostCenterData::from([
            'code' => 'CC-C',
            'name' => 'C',
            'type' => 'department',
            'parent_uid' => null,
            'is_active' => true,
        ]), $cc->uid);

        assertDatabaseHas('cost_centers', ['id' => $cc->id, 'parent_id' => null]);
    });

    it('returns an error when the cost center is not found (service)', function () {
        $response = ccService()->update(UpdateCostCenterData::from([
            'code' => 'X',
            'name' => 'X',
            'type' => 'department',
            'parent_uid' => null,
            'is_active' => true,
        ]), 'missing-uid');

        expect($response['error'])->toBeTrue();
    });

    it('updates via the endpoint (e2e)', function () {
        ccActor();
        $cc = ccMake(['code' => 'CC-E', 'name' => 'Before']);

        $this->putJson("/api/accounting/cost-centers/{$cc->uid}", [
            'code' => 'CC-E',                 // same code is allowed (unique rule ignores self)
            'name' => 'After',
            'type' => 'department',
            'parent_uid' => null,
            'is_active' => true,
        ])->assertStatus(201);

        assertDatabaseHas('cost_centers', ['id' => $cc->id, 'name' => 'After']);
    });
});

describe('toggleStatus', function () {
    it('flips an active cost center to inactive (service)', function () {
        $cc = ccMake(['code' => 'CC-T', 'is_active' => true]);

        $response = ccService()->toggleStatus($cc->uid);

        expect($response['error'])->toBeFalse()
            ->and($response['message'])->toBe(__('global.costCenterUpdated'));
        assertDatabaseHas('cost_centers', ['id' => $cc->id, 'is_active' => false]);
    });

    it('flips an inactive cost center to active (service)', function () {
        $cc = ccMake(['code' => 'CC-T2', 'is_active' => false]);

        ccService()->toggleStatus($cc->uid);

        assertDatabaseHas('cost_centers', ['id' => $cc->id, 'is_active' => true]);
    });

    it('returns an error when the cost center is not found (service)', function () {
        $response = ccService()->toggleStatus('missing-uid');

        expect($response['error'])->toBeTrue();
    });

    it('toggles via the endpoint (e2e)', function () {
        ccActor();
        $cc = ccMake(['code' => 'CC-TE', 'is_active' => true]);

        $this->patchJson("/api/accounting/cost-centers/{$cc->uid}/toggle")
            ->assertStatus(201);

        assertDatabaseHas('cost_centers', ['id' => $cc->id, 'is_active' => false]);
    });
});

describe('delete', function () {
    it('deletes a cost center (service)', function () {
        $cc = ccMake(['code' => 'CC-D', 'name' => 'ToDelete']);

        $response = ccService()->delete($cc->uid);

        expect($response['error'])->toBeFalse()
            ->and($response['message'])->toBe(__('global.costCenterDeleted'));
        assertDatabaseMissing('cost_centers', ['id' => $cc->id]);
    });

    it('returns an error when deleting a missing cost center (service)', function () {
        $response = ccService()->delete('missing-uid');

        expect($response['error'])->toBeTrue();
    });

    it('deletes via the endpoint (e2e)', function () {
        ccActor();
        $cc = ccMake(['code' => 'CC-DE', 'name' => 'Del']);

        $this->deleteJson("/api/accounting/cost-centers/{$cc->uid}")
            ->assertStatus(201);

        assertDatabaseMissing('cost_centers', ['id' => $cc->id]);
    });
});
